### ISSUE TITLE
[BUG] Fehlende Berechtigung für Eintragung in den Spieltagsbericht

### ISSUE THREAD

**Issue by Office-FD** [floorballdeutschland/saisonmanager-feedback#1]
### Beschreibe den Fehler
Liga 1315
Team 5593
Spieltags ID 10412

Spieltag der SG Rangsdorf/ Mellensee gegen SG Regenbogen am 19.02.2023. Der RSV Mellensee ist als Ausrichter gesetzt. Der VM des RSV Mellensee kann aber den Spielbericht nicht eintragen.

### Erwartetes Verhalten
Der VM des ausrichtenden Verein soll den Spielbericht eingeben können.

### Tatsächliches Verhalten
Der VM des ausrichtenden Vereins hat keine Berechtigung für die Spieltagseingabe

### Zusätzliche Informationen

**Comment by janhoffmann** [comment]
**Kontext**
https://saisonmanager.de/fvbb/1315-regionalliga-floorballbb-herren-challengeround
Regionalliga FloorballBB Herren Challengeround
https://saisonmanager.de/fvbb/1315-regionalliga-floorballbb-herren-challengeround/spiel/29953

**Comment by Office-FD** [comment]
Stimmt, ich gebe beim nächsten Mal den Link mit an. Sorry

**Comment by janhoffmann** [comment]
@Office-FD Bitte per E-Mail den Benutzernamen nachliefern.

**Comment by janhoffmann** [comment]
user 1071, club 36

**Comment by janhoffmann** [comment]
@Office-FD Habe das Spiel mit in alter Version in der Datenbank angesehen und lokal ausprobiert.
Mit angegebenen Nutzer, wird mir der Knopf zum Bearbeiten angezeigt.

![image](https://user-images.githubusercontent.com/1494946/221608100-129b2afc-e51e-46bc-9848-a44f8f096f4a.png)

Bitte beim Benutzer nachfragen:
- Welches Betriebssystem wird eingesetzt, welche Version
- Welcher Browser wird eingesetzt, welche Version
- Sind irgendwelche Browsererweiterungen (AdBlock, Ghostery, ...) aktiv?
- Hat der Benutzer versucht sich ab und wieder an zu melden?

**Comment by dkehne** [comment]
@Office-FD hat der VM von Mellensee die Daten schon geliefert?

**Comment by Office-FD** [comment]
Nein, hat er nicht. Ist aber mittlerweile erledigt. Spiel wurde durch die SBK FVBB eingetragen

**Comment by dkehne** [comment]
Okay wir schließen hier bis das Thema nochmal aufkommt (falls es nochmal so sein sollte)
