### ISSUE TITLE
Spiel Nr 11 in der Liga 1314 im SM nicht abschließbar[BUG]

### ISSUE THREAD

**Issue by Office-FD** [floorballdeutschland/saisonmanager-feedback#2]
### Beschreibe den Fehler
SpieltagsID 10395

Das Spiel Nummer 11 in der Liga 1314 (Eisbären gegen Laikas) hängt im Modus „Eingabe“ obwohl es vom Verein und sowohl mir als SBK beendet wurde.

### Erwartetes Verhalten
Spiel wird mit der Option "Spiel beenden" durch den Ausrichter beendet. "Live" Einblendung vom Spielstand verschwindet. Das Spiel kann abgeschlossen werden.

### Tatsächliches Verhalten
"Live" Einblendung weiterhin sichtbar auch nachdem Ausrichter und SBK das Spiel abgeschlossen haben.

### Zusätzliche Informationen
möglicherweise wurde das Spiel nicht direkt vom Ausrichter abgeschlossen, sondern direkt von der SBK beendet.

![image](https://user-images.githubusercontent.com/126473201/221609655-24466522-ddec-4408-9ab1-e78e19e5595c.png)

**Comment by Office-FD** [comment]
Spiel ID: https://saisonmanager.de/fvbb/1314-regionalliga-floorballbb-herren-masterround/spiel/29936

**Comment by janhoffmann** [comment]
Bei der Eingabe des Spiels wurde nicht mit den Knöpfen gearbeitet (Nächste Pause, Nächster Spielabschnitt)

![image](https://user-images.githubusercontent.com/1494946/221827311-7249e08b-5798-4e4c-8438-74f9608d49d3.png)

Das sieht man klar an der Angabe unter der Live Anzeige

![image](https://user-images.githubusercontent.com/1494946/221827647-2e034911-7d15-4277-bde2-f7fdbfa66810.png)

Es wurde nie in die erste Pause gewechselt und genau so nie das Spiel abgepfiffen markiert.


Ich habe das jetzt von Hand geändert.
