### ISSUE TITLE
[WANTED] Spieltag löschen

### ISSUE THREAD

**Issue by signpainter** [floorballdeutschland/saisonmanager-feedback#21]
### Motivation
Ein einmal erstellter Spieltag kann als SBK-Account nicht gelöscht werden. Da dies durchaus aus Versehen passieren kann oder da sich der Spielplan im Nachhinein geändert hat, sollte es die Möglichkeit geben einen Spieltag zu löschen.

### Vorgeschlagene Lösung
Entweder in der Spieltagsübersicht oder unter Spieltag bearbeiten sollte ein Button zum Löschen des Spieltags und evtl. aller zugeordneten Spiele hinzugefügt werden.

### Alternativen
- Mail an it@floorball.de

### Links zu relevanten Seiten
https://saisonmanager.de/verwaltung/ligen/1294/spielplan - beinhaltet testweise einen Spieltag, der nicht gelöscht werden kann

Wichtig: Nenne keine Personenbezogene oder sensible Daten. Diese sind nach anlegen des Issues an it@floorball.de zu senden

**Comment by janhoffmann** [comment]
@signpainter Danke für die Meldung. Wir hatten das Feature tatsächlich schon vorbereitet und es mit dem nächsten Release mitgenommen. Ich habe es mal vorgezogen in Release 2.10.1 und es gerade veröffentlicht.

![image](https://github.com/floorballdeutschland/saisonmanager-feedback/assets/1494946/ec47a21a-2363-4a1b-81e2-b4a21c4c8613)

Hier kannst du leere Spieltage löschen. Hat der Spieltag noch Spiele zugeordnet, müssten diese zuerst gelöscht werden.
