### ISSUE TITLE
[WANTED] Klassifizierung der Tabelle anpassbar gestalten

### ISSUE THREAD

**Issue by jasp-priv** [floorballdeutschland/saisonmanager-feedback#28]
### Motivation

Die Klassifizierung innerhalb einer Tabelle kann durchaus abweichen von der in der FD SPO§14 angegebenen. So wird in den Trophys der direkte Vergleich höher bewertet. Ebenso im Spielbetrieb des FLV-SH.

Zur Vermeidung von Verwirrung und Erleichterung der Arbeit auf den Trophys wird vorgeschlagen:

### Vorgeschlagene Lösung

Einstellbare Presets der Liga, wie diese klassifiziert werden zur Verfügung zu stellen.

Die Presets sollten nur von Admins / SBK-FD gesetzt werden können.
Die Presets sollten von SBK Accounts eingesehen werden können.
Alle SBK Accounts sollten ein Preset einer Liga zuweisen können

### Links zu relevanten Seiten
[SPO-FD](https://floorball.de/download/filebase/ordnungen/2022-08-24-SPO-FD-2022-2023.pdf)
[SPO-FLV-SH](https://floorball-sh.de/assets/Downloads/DFB-SBK-v2.pdf)
Turnierreglement Trophies von FD §3.5

**Comment by signpainter** [comment]
Duplicate of #16

**Comment by dkehne** [comment]
Mit Blick auf Issue #16 würde ich vorschlagen, dass wir es erstmal nicht komplett flexibel gestalten, sondern - wie @janhoffmann bereits angefangen hat - ggf. höchsten weitere Wertungsregeln hinzuzufügen. Sollten also weitere Wertungsregeln gebraucht werden, bitte ein Issue dafür erstellen. Ich schließe hier.
