### ISSUE TITLE
Öffnen des Spieles 29676 [BUG]

### ISSUE THREAD

**Issue by Office-FD** [floorballdeutschland/saisonmanager-feedback#3]
### Beschreibe den Fehler
Falsche Eingabe in den SM und vorzeitiger Abschluss des Spieles
https://saisonmanager.de/fvh/1275-hessenliga-u9-kt/spiel/29676

Bitte einmal das Spiel wieder öffnen.

**Comment by janhoffmann** [comment]
Ist kein Bug, siehe E-mail.
