### ISSUE TITLE
[BUG] Verlängerung in Spielberichten

### ISSUE THREAD

**Issue by chefkoch24** [floorballdeutschland/saisonmanager-feedback#31]
### Beschreibe den Fehler
Es existieren Spiel die nach Verlängerung entschieden wurden, allerdings im Spielbericht alle Tore während der regulären drei Drittel gefallen sind. 

### Schritte zum Reproduzieren
1. Gehe zu Spielbericht: https://saisonmanager.de/fvd/1204-1-fbl-herren/spiel/27633
3. Siehe Ergebnis und letzte Tor

### Erwartetes Verhalten
Das letzte Tor hätte in der Verlängerung eingetragen werden müssen

### Tatsächliches Verhalten
Das letzte Tor wurde im 3. Drittel eingetragen

### Zusätzliche Informationen
<img width="1128" alt="Screenshot 2023-06-23 at 17 02 19" src="https://github.com/floorballdeutschland/saisonmanager-feedback/assets/26713841/42567872-abea-435b-bb26-bed8eec967a7">
<img width="1134" alt="Screenshot 2023-06-23 at 17 02 09" src="https://github.com/floorballdeutschland/saisonmanager-feedback/assets/26713841/6ad5f001-7393-4f19-bf42-7b35e9fa7b52">

Wichtig: Nenne keine Personenbezogene oder sensible Daten. Diese sind nach anlegen des Issues an it@floorball.de zu senden

**Comment by janhoffmann** [comment]
Fehler bei der Eingabe, Meldung bitte an zuständige SBK.
