### ISSUE TITLE
[WANTED] Account für Vereine anlegen, verwalten und löschen

### ISSUE THREAD

**Issue by BarbaraBrandmaier-FVB** [floorballdeutschland/saisonmanager-feedback#32]
### Motivation
Im alten Saisonmanager war die Accounterstellung für die SBK und VM möglich. Grundsätzlich würde reichen, wenn die Funktion zumindest wieder für die SBK möglich ist, damit neue Vereine oder neue Trainer eine Möglichkeit erhalten, ihr(e) Team(s) zu verwalten.  Bislang ging dies nur mit Mail an die Geschäftsstelle, die mit den nötigen Daten einen Account erstellen hat lassen.
Auch die Accounts zu löschen wäre manchmal nicht schlecht, wenn diese den Verein verlassen. Datenschutzrechtlich wäre das sogar deutlich besser, als sie als Karteileiche liegen zu lassen.

### Vorgeschlagene Lösung
Accounterstellung sollte für die SBK´s möglich sein. Gerne auch für VM. Löschen ggf. nur für SBK.

**Comment by dkehne** [comment]
Ist auch bereits in #8 geöffnet worden und damit ein Duplikat. Schließe es hier, dann ist es aber auch in dem anderen Issue verlinkt
