### ISSUE TITLE
[WANTED] Spielerverwaltung - Spieler aus Datenbank löschen

### ISSUE THREAD

**Issue by BarbaraBrandmaier-FVB** [floorballdeutschland/saisonmanager-feedback#33]
### Motivation
Viele Vereine wollen, dass sie Spieler, die aus dem Verein austreten und mit Floorball aufhören, aus der Datenbank löschen können. Besonders im Jugendbereich hören viele Kinder auf, ein Wechsel ist dort ausgeschlossen. Gerne kann der Fall ausschließlich über die SBK laufen, damit nicht unnötig Daten gelöscht werden. 

### Vorgeschlagene Lösung
Die Spielerverwaltung sollte so gesteuert werden, damit nicht jeder die Datensätze der Spielerinnen und Spieler löschen kann, dennoch wäre es deutlich einfach, die Karteileichen im Griff zu haben.

Wichtig: Nenne keine Personenbezogene oder sensible Daten. Diese sind nach anlegen des Issues an it@floorball.de zu senden

**Comment by signpainter** [comment]
Das Problem mit löschen ist, dass dann alle Datensätze, wie Spielberichtsbögen, Lizenzverläufe, etc. nicht mehr gültig wären. Es gibt ja bisher die Ablage, in der alle inaktiven Spieler landen. Da kann man auch heute schon Spieler "hintransferieren".

**Comment by janhoffmann** [comment]
Genau das ist auch das gewünschte Vorgehen.

Die Spieler sollen nach einiger Zeit in die Ablage transferiert werden und können von dort ggf. wieder aktiviert werden, falls sie nochmal wieder starten.

@signpainter hat den Hintergrund hier schon gut erklärt.

**Comment by BarbaraBrandmaier-FVB** [comment]
Ok, dann werden wir das so handhaben. 
Danke.

**Comment by janhoffmann** [comment]
@BarbaraBrandmaier-FVB ich schließe das Ticket dann mal.
