### ISSUE TITLE
[WANTED] Kontrolle durch SBK - erforderlich?

### ISSUE THREAD

**Issue by BarbaraBrandmaier-FVB** [floorballdeutschland/saisonmanager-feedback#34]
### Motivation
Ist Punkt 4 bei der Spielberichtseingabe "Kontrolle durch SBK" wirklich erforderlich bzw. gibt es Probleme, wenn dies nur durch die SBK erledigt wird?

### Vorgeschlagene Lösung
Direkte Lösung nicht, eher Beantwortung der Funktion.

**Comment by janhoffmann** [comment]
@BarbaraBrandmaier-FVB Leider wird bei der Eingabe der Spielberichte nicht überall sorgfältig gearbeitet. Der Schritt soll es den SBKs erlauben anzusetzen und die Spiele nochmal kurz zu kontrollieren und zu korrigieren.

Das Ziel ist es natürlich im Saisonmanager immer die richtigen Werte zu haben. Da wir immer mehr Richtung live-Eingabe arbeiten möchten, sollte der Schritt euch die Möglichkeit geben die Ansprechpartner vor Ort zu schulen und ggf. nochmal zu erklären, was schief gelaufen ist.

Was meinst du mit "wenn dies nur durch die SBK erledigt wird"?

**Comment by BarbaraBrandmaier-FVB** [comment]
Hi Jan,
sorry, da war ein Tippfehler dabei. Die Frage war:
Gibt es Probleme, wenn dies nicht durch die SBK erledigt wird.

Der Rest leuchtet mir ein. Im Großen und Ganzen funktioniert die Eintragung auch, außer bei Internetproblemen (was ich selbst feststellen musste). Da ist dann aber auch der SBK Zugang Machtlos gewesen und ich musste mich eh ans Office bzw. an dich wenden.

**Comment by dkehne** [comment]
Wenn ich das richtig sehe, dass ist es ja keine Pflicht für euch als SBK die Spielberichte zu prüfen oder? Die Ergebnisse sind ja auch vorher schon im Saisonmanager sichtbar. Es ist also quasi eine optionale Funktion für die SBKen, die gerne so eine Art "4-Augen-Prinzip" umsetzen wollen.

Korrigiert mich @BarbaraBrandmaier-FVB / @janhoffmann falls ich falsch liege.
