### ISSUE TITLE
[WANTED] Übersichtlicherer Darstellung der bearbeiteten Lizenzen und mehr Details

### ISSUE THREAD

**Issue by signpainter** [floorballdeutschland/saisonmanager-feedback#36]
### Motivation
Nachdem die Lizenzen aktuell bearbeitet wurden, wird im Anschluss nur noch angezeigt, wer für welches Teams eine Lizenz hat und wann der/die SpielerIn geboren wurde. Für weitere Informationen, wie wann die Lizenz beantragt oder genehmigt wurde, durch wen dies erledigt wurde und welche weiteren Lizenzen die SpielerIn hat, muss man umständlich über die Vereinübersicht zum jeweiligen Spieler navigieren.
Die Informationen sind teils notwendig, da es auf LV Ebene zusätzliche Lizenzregeln gibt, die bspw. die Zweitlizenzregelung von FD weiter einschränkt. Dafür muss es möglich sein, zu prüfen, ob ein Spieler nachdem er die Lizenz erhalten hat, unerlaubterweise weitere Lizenzen bspw. in einem anderen LV beantragt und genehmigt bekommen hat.

Desweiteren ist die aktuelle Darstellung recht unübersichtlich, da die Vereine in mehreren Spalten angezeigt werden und floaten. Entsprechend schwierig ist es einen Sichtanker für die mentale Sortierung zu finden. Insbesondere auf kleinen Viewports werden durch die beiden Spalten teils sogar die Namen abgekürzt.

### Vorgeschlagene Lösung
Eine Tabelle als Anzeige wie in der alten Version des Saisonmanagers war so schlecht nicht. Alle Teams in alphabetischer Reihenfolge untereinander, die Teamnamen evtl. als Zwischenheader. Dann sollte auch weiterhing ausreichend Platz sein, um die Informationen nebeneinander bzw. über zwei Zeilen anzuzeigen.

### Alternativen

Wichtig: Nenne keine Personenbezogene oder sensible Daten. Diese sind nach anlegen des Issues an it@floorball.de zu senden

**Comment by dkehne** [comment]
Duplikat von #27 - gerne dort nochmal ergänzen, was dir in dem Issue noch fehlt @signpainter, das Thema der möglichen weiteren Lizenzen haben ich als Kommentar ergänzt. Ich schließe hier.
