### ISSUE TITLE
[BUG] Spielberichtseingabe mit Verlängerung eintragen

### ISSUE THREAD

**Issue by dkehne** [floorballdeutschland/saisonmanager-feedback#4]
### Beschreibe den Fehler
Bei Anhaken der Verlängerung wird erst nach dem Deaktivieren und erneutem Aktivieren der Option "Verlängerung", diese auch eingetragen.

### Erwartetes Verhalten
Die Verlängerung sollte direkt eingetragen werden, wenn diese Angehakt wird.

### Tatsächliches Verhalten
Ich muss erst einmal deaktivieren, damit dies möglich ist.

**Comment by janhoffmann** [comment]
Von wann ist diese Meldung?
Der Fehler wurde aus meiner Sicht in Release 2.9.8 am 21. März bereits behoben.

**Comment by chefkoch24** [comment]
Zu spät gesehen das es ein ähnliches Issue schon gab: https://github.com/floorballdeutschland/saisonmanager-feedback/issues/31

**Comment by janhoffmann** [comment]
In Release 2.9.8 behoben.
