### ISSUE TITLE
[BUG] Impressum Seite linkt nicht auf Impressum

### ISSUE THREAD

**Issue by rn5f107s2** [floorballdeutschland/saisonmanager-feedback#55]
### Beschreibe den Fehler
Der Impressum Knopf führt nicht zu einem Impressum
### Schritte zum Reproduzieren
1. Gehe zu https://saisonmanager.de/
2. Klicke auf Impressum

### Erwartetes Verhalten
Nach dem Klick auf Impressum wird ein Impressum angezeigt

### Tatsächliches Verhalten
Es wird kein Impressum angezeigt

**Comment by Office-FD** [comment]
Link wurde gefixt.

**Comment by rn5f107s2** [comment]
Danke!
