### ISSUE TITLE
[BUG] Zertifikat von https://archiv.saisonmanager.de/ kaputt

### ISSUE THREAD

**Issue by rn5f107s2** [floorballdeutschland/saisonmanager-feedback#56]
### Beschreibe den Fehler
Zertifikat von  https://archiv.saisonmanager.de/ kaputt

### Schritte zum Reproduzieren
1. Gehe zu https://archiv.saisonmanager.de/

### Erwartetes Verhalten
Die Website wird angezeigt

### Tatsächliches Verhalten
Eine Warnung das dies keine sichere verbindung ist wird angezeigt 

### Zusätzliche Informationen
![Screenshot_20241027-115531~2.png](https://github.com/user-attachments/assets/4007464a-0bec-4167-8f8b-f9113be30f48)

**Comment by janhoffmann** [comment]
fixed

**Comment by rn5f107s2** [comment]
Das Zertifikat ist schon wieder abgelaufen

**Comment by janhoffmann** [comment]
![image](https://github.com/user-attachments/assets/de0d7285-b72a-4d09-a1cb-6076d7c02775)
