### ISSUE TITLE
[BUG] Abgelehnte Lizenzen können nicht neu beantragt werden

### ISSUE THREAD

**Issue by dkehne** [floorballdeutschland/saisonmanager-feedback#7]
### Beschreibe den Fehler
Das Problem ist, dass bei vorab abgelehnten Lizenzen (stehen dann auf „abgelehnt“) keine Neubeantraung einer Lizenz möglich ist. Der Fall kommt immer mal wieder vor, weil Spieler*innen ggf. bestimmte Unterlagen nicht mit eingereicht haben, die für die Genehmigung der Lizenz notwendig sind oder zum Zeitpunkt der Beantragung noch zu jung sind.

### Erwartetes Verhalten
Es sollte die Möglichkeit geben Lizenzen mit dem Status "abgelehnt" neu beantragt werden können.

**Comment by janhoffmann** [comment]
Die Funktion existiert bereits für andere Fälle (zurückgezogene Anträge), ist aber aktuell für "abgelehnt" deaktiviert, weil es dafür keinen sinnvollen Anwendungsfall gibt.

In deinem Beispiel ist ja auch die Frage:
Wäre es dann nicht Aufgabe der SBKs/Office die Lizenz nachträglich zu erteilen, wenn Unterlagen nachgereicht werden?

**Comment by janhoffmann** [comment]
wontfix
